# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='wines',
        ),
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='wine',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='wine',
            name='foods',
            field=models.ManyToManyField(related_name='wines', to='api.Food'),
        ),
    ]
